### ISSUE TITLE
docker-vm templates failing with error

### ISSUE THREAD

**Issue by impurush** [instruqt/templates#5]
I have tried to replicate the docker-vm template and changed to docker-splunk, followed the steps to push the tracks. However it is failing with ←[1;31m[ERROR]←[0m Entity not found. I have tried in both Linux and Windows but got the same error. Could you please help me to redirect on how to solve this issue. Thanks in advance,Purush

**Comment by scarolan** [comment]
@impurush  please contact us in Instruqt slack and we'll help you get this working if it is still a blocker.
